sudo: enabled
language: cpp
matrix:
    allow_failures:
        - os: osx  
    include:
        # works on Precise and Trusty
        - os: linux
          env: 
             - MATRIX_EVAL="sudo apt-get install g++-4.9 && CC=gcc-4.9 && CXX=g++-4.9"
#    # works on Precise and Trusty
        - os: linux
          env:
             - MATRIX_EVAL="sudo apt-get install g++-5 && CC=gcc-5 && CXX=g++-5"
#    # works on Precise and Trusty
        - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-6
          env:
             - MATRIX_EVAL="sudo apt-get install g++-6 && CC=gcc-6 && CXX=g++-6"
#           # works on Precise and Trusty
        - os: osx
#            osx_image: xcode8
          env:
             - MATRIX_EVAL="brew install gcc5 --without-multilib && CC=gcc-5 && CXX=g++-5"
        - os: osx
          #         osx_image: xcode8
          env:
             - MATRIX_EVAL="brew install gcc6 --without-multilib && CC=gcc-6 && CXX=g++-6"
        - os: osx
          #         osx_image: xcode8
          env:
             - MATRIX_EVAL="brew install gcc --without-multilib && CC=gcc-7 && CXX=g++-7"
before_install:
  - eval $MATRIX_EVAL
      - if [ $TRAVIS_OS_NAME = linux ]; then 
          wget ftp://ftp.gnu.org/gnu/gsl/gsl-2.4.tar.gz;
          tar -xzvf gsl-2.4.tar.gz;
          pushd gsl-2.4 && ./configure --prefix=/usr && make && sudo make install && popd;
          fi
      - if [ $TRAVIS_OS_NAME = osx ]; then travis_wait brew install gsl; fi

script: make CXX=$COMPILER
