sudo: required
language: cpp
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: osx
      osx_image: xcode8
      env:
      	- MATRIX_EVAL="brew install gcc5 --without-multilib && CC=gcc-5 && CXX=g++-5"
before_install:
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      wget ftp://ftp.gnu.org/gnu/gsl/gsl-2.4.tar.gz;
      tar -xzvf gsl-2.4.tar.gz;
      pushd gsl-2.4 && ./configure --prefix=/usr && make && sudo make install && popd;
      fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait brew install gsl; fi

script: make CXX=$COMPILER
