sudo: required
before_install:
    - wget ftp://ftp.gnu.org/gnu/gsl/gsl-*.*.tar.gz
    - tar -zxvf gsl-*.*.tar.gz
    - cd gsl-1.7 & ./configure & make check & make install

language: cpp

compiler:
  - clang++
  - g++

script: make

